### PR TITLE
Add behavior to gesture

### PR DESCRIPTION
**Pull request by chauvansang1997**
I have added behavior to gesture to support parent gesture

### CODE REVIEW

**Review by taodo2291 — APPROVED** [review]

**Comment by taodo2291** [comment]
Hi Sang,
Thank you for your contribution. 
Did you graduate from UIT?.

**Comment by chauvansang1997** [comment]
Yes, are you Vietnamese?

**Comment by taodo2291** [comment]
I graduated from UIT too (CNPM04). 

Nice to know you :)

**Comment by chauvansang1997** [comment]
I'm from CNPM10. Nice to meet you too. I hope meet you soon :)).

**Pull request merged**
